### PR TITLE
Bundled update

### PR DESCRIPTION
**Pull request by AleksueiR**
- use Observables for internal and external events
- update main sample page
- added two more CESI samples
- add API section to docs

---
This change is [Reviewable](https://reviewable.io/reviews/ramp-pcar/dqvue/2)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 16 of 17 files at r1.
Review status: 16 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/api.md, line 1 at r1](https://reviewable.io:443/reviews/ramp-pcar/dqvue/2#-L0eG38Q4LuJrNNUztZe:-L0eG38RMPZysFyHdfYs:b-nkn2i4) ([raw file](https://github.com/ramp-pcar/dqvue/blob/b6f1742160021f2f35ffdb6fd7851cf7e467b908/docs/api.md#L1)):*
> ```Markdown
> ---
> ```

I haven't read over this file in source form, is it any different from the last time I looked at the draft?

---

*[docs/config.js, line 24 at r1](https://reviewable.io:443/reviews/ramp-pcar/dqvue/2#-L0eEbA49AstGJHcd--j:-L0eEbA5WhfGql58foEC:b-wi210y) ([raw file](https://github.com/ramp-pcar/dqvue/blob/b6f1742160021f2f35ffdb6fd7851cf7e467b908/docs/config.js#L24)):*
> ```JavaScript
>     plugins: [
>         evanyou() /* ,
>         docuteIframe({
> ```

Dead code you forgot to remove or intentionally left behind?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ramp-pcar/dqvue/2)*

**Comment by AleksueiR** [comment]
Review status: 15 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/api.md, line 1 at r1](https://reviewable.io:443/reviews/ramp-pcar/dqvue/2#-L0eG38Q4LuJrNNUztZe:-L0iogOMqOYPKoL7RowT:b-a045s4) ([raw file](https://github.com/ramp-pcar/dqvue/blob/b6f1742160021f2f35ffdb6fd7851cf7e467b908/docs/api.md#L1)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

I haven't read over this file in source form, is it any different from the last time I looked at the draft?
</blockquote></details>

Mostly the same; I just added information on how to generate chart tables.

---

*[docs/config.js, line 24 at r1](https://reviewable.io:443/reviews/ramp-pcar/dqvue/2#-L0eEbA49AstGJHcd--j:-L0ioyxmE8IAcIvJNhcu:bnfg8z1) ([raw file](https://github.com/ramp-pcar/dqvue/blob/b6f1742160021f2f35ffdb6fd7851cf7e467b908/docs/config.js#L24)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Dead code you forgot to remove or intentionally left behind?
</blockquote></details>

Forgot. Removed. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ramp-pcar/dqvue/2)*

**Comment by alyec** [comment]
Reviewed 1 of 17 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/index.html, line 15 at r2](https://reviewable.io:443/reviews/ramp-pcar/dqvue/2#-L0jz8HGVsXKViyQElCA:-L0jz8HGVsXKViyQElCB:b-dimzgo) ([raw file](https://github.com/ramp-pcar/dqvue/blob/eee351ad573511cdbcfa21deea05325bff63a91a/docs/index.html#L15)):*
> ```HTML
>   <div id="app"></div>
>   <script src="https://unpkg.com/docute@3/dist/docute.js"></script>
>   
> ```

remove?  looks the same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ramp-pcar/dqvue/2)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/index.html, line 15 at r2](https://reviewable.io:443/reviews/ramp-pcar/dqvue/2#-L0jz8HGVsXKViyQElCA:-L0k6VSiN46o1zYtIlGi:b-hfpv0l) ([raw file](https://github.com/ramp-pcar/dqvue/blob/eee351ad573511cdbcfa21deea05325bff63a91a/docs/index.html#L15)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

remove?  looks the same as above
</blockquote></details>

removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ramp-pcar/dqvue/2)*

**Comment by AleksueiR** [comment]
Heartbeat integration should work now.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ramp-pcar/dqvue/2#-:-L0kA2OU3cEb-PIygEO4:bbgtw8f)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ramp-pcar/dqvue/2#-:-L0kAlDSgA3aBt99ucpl:bnfp4nl)*

**Pull request merged**
