### PR TITLE
Auto update table on series toggle

### PR DESCRIPTION
**Pull request by spencerwahl**
For issue #7

---
This change is [Reviewable](https://reviewable.io/reviews/ramp-pcar/dqvue/23)

### CODE REVIEW

**Comment by AleksueiR** [comment]
:lgtm: 

Please, add some comments to the new things you are adding.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/components/chart-table.vue, line 136 at r1](https://reviewable.io:443/reviews/ramp-pcar/dqvue/23#-L5TacLJ-uEdd7cjCwrU:-L5TacLKpkrCjaZP8eIk:bvocxmc) ([raw file](https://github.com/ramp-pcar/dqvue/blob/31f9f80bc9331c020270d7063842053e7305226d/src/components/chart-table.vue#L136)):*
> ```Vue
>         }
> 
>         let showTable = false;
> ```

Use `some` to avoid the intermediate variable.

```js
if (!this.dvchart.highchart.series.some(series => series.visible)) {
    this.highchartsDataTable.innerHTML = '';
    return;
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ramp-pcar/dqvue/23#-:-L5TbOGtp4nig_OHWhDb:b-3vkh4j)*

**Comment by spencerwahl** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/components/chart-table.vue, line 136 at r1](https://reviewable.io:443/reviews/ramp-pcar/dqvue/23#-L5TacLJ-uEdd7cjCwrU:-L5TpGqWgCzVx1vOpjKe:b-896fix) ([raw file](https://github.com/ramp-pcar/dqvue/blob/31f9f80bc9331c020270d7063842053e7305226d/src/components/chart-table.vue#L136)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Use `some` to avoid the intermediate variable.

```js
if (!this.dvchart.highchart.series.some(series => series.visible)) {
    this.highchartsDataTable.innerHTML = '';
    return;
}
```

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ramp-pcar/dqvue/23)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/components/chart.vue, line 267 at r2](https://reviewable.io:443/reviews/ramp-pcar/dqvue/23#-L5Tpvsat3PgVOjuvuRG:-L5Tpvsat3PgVOjuvuRH:bb05p9w) ([raw file](https://github.com/ramp-pcar/dqvue/blob/e2e846f093dfecbe324d181b4ee2637edce3c3c3/src/components/chart.vue#L267)):*
> ```Vue
> 
>     // runs the original `hide` or `show` series event and then pushes an event into the stream
>     private _setHideShowHandler(originalHandler: (() => void) | null): void {
> ```

`originalHandler` is guaranteed to be a function because of the config defaults we are merging into the chart config, unless the author explicitly sets it as `undefined` of course. No need for a falsy check and param type doesn't need `null` option.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ramp-pcar/dqvue/23)*

**Comment by spencerwahl** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/components/chart.vue, line 267 at r2](https://reviewable.io:443/reviews/ramp-pcar/dqvue/23#-L5Tpvsat3PgVOjuvuRG:-L5Tqs8SfMeEgyEn0WOk:b-896fix) ([raw file](https://github.com/ramp-pcar/dqvue/blob/e2e846f093dfecbe324d181b4ee2637edce3c3c3/src/components/chart.vue#L267)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

`originalHandler` is guaranteed to be a function because of the config defaults we are merging into the chart config, unless the author explicitly sets it as `undefined` of course. No need for a falsy check and param type doesn't need `null` option.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ramp-pcar/dqvue/23)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ramp-pcar/dqvue/23)*

**Pull request merged**
